### ISSUE TITLE
Setting up notification sounds for xfce?

### ISSUE THREAD

**Issue by ron0studios** [erick2red/gnome-calendar#5]
Hi there! 
I am currently using an Xfce desktop environment ( w/ manjaro) and have had some trouble playing notification audio during a reminder. I already have canberra installed, and have event sounds enabled in the settings. I am also using a [sound theme](https://aur.archlinux.org/packages/sound-theme-smooth/). How can I get my notification sounds to play, is there some sort of specific file that the program is trying to play but it can't be found?
Thanks in advance!

**Comment by ron0studios** [comment]
I also tried the evolution calendar, and the alarm sound works in that app. Figuring that the function that plays the alarm sound is from Evolution, I don't understand why no sound is playing.

**Comment by erick2red** [comment]
Hi,

I'm no longer maintaining GNOME Calendar and development have moved to GNOME's Gitlab.
Below is the link for the issues page in the repository there.

[GNOME Calendar's Issues](https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues)

You can try and reach the current developers there, although by the description of your issue I suggest you get in touch with the distribution developers in the first place, meaning with the team behind Manjaro Linux.

**Comment by ron0studios** [comment]
Ah I see, thank you! In that case you should probably archive this repo
